name: Auto Build Latest Image

on:
  push:
    branches:
      - main1

permissions: write-all

jobs:
  call-build-push:
    uses: ./.github/workflows/call-image-build.yaml
    with:
      ref: ${{ github.ref }}
      tag: latest
      push: true
    secrets: inherit
