name: prOrPush

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # checkout the changed code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        id: go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
        with:
          go-version: '1.21.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: login hub.docker
        run: |
          docker login -u inspurwyd  -p  dckr_pat_yMRt21vCZj0PlDl14xJiqSOHeVg

      - name: build & push images
        run: |
          make image
